name: Auto Update Live Data

on:
  schedule:
    # Spustiť každých 5 minút
    - cron: '*/5 * * * *'
  workflow_dispatch: # Umožniť manuálne spustenie

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Run data ingest
        run: yarn ingest
        env:
          NODE_ENV: production
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/live/*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Auto-update: Live data $(date +'%Y-%m-%d %H:%M:%S')" && git push)
